### ISSUE TITLE
Learn Suggestion

### ISSUE THREAD

**Issue by MartinCrane** [learn-co-curriculum/table-relations#15]
This isn't lesson specific, but it occurred to me how helpful it would be if there were a central html file or git repository with all the external resource links organized by topic. I would love to be able to go in a grab them all into bookmarks folders to save for future use, yet I find within the workflow of learn, my focus is on completing lessons and not exploring them as much, so I sometimes skip over them.

Just a thought

MC

**Comment by jenmyers** [comment]
Hi there! This request sounds like an improvement to or a problem with the Learn platform.

Our product team can help you with this. You can reach them at support@learn.co.

Raising issues on GitHub, like you've done here, should happen when there are problems with the curriculum itself (doesn't work, throws a Ruby error, etc.).

If, on the other hand, we've misunderstood the purpose of this request, please re-open this issue, provide any additional information you can to clarify our error, and we will try to find a fix.
