### ISSUE TITLE
Change from pets table to cats table

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/table-relations#16]
Step 2: Creating the Owners Table
First, we need to create our owners table. An owner should have an ID that is a primary key integer and a name that is text:

CREATE TABLE owners (id INTEGER PRIMARY KEY, name TEXT);
Now that we have our owners table, we can add a foreign key column to the pets table.
*************************
Error:   Last sentence should read "foreign key column to the cats table". 
The tables that were created were cats and owners. There is no 'pets table' for this example.

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! In this case, the reference is not to the specific name of the table but a general reference to the type of data the table contains. We can consider clarifying this in future versions of the curriculum. 

As always, thanks for contributing! 💙
