### ISSUE TITLE
Small Typo: "R"uby 

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/table-relations#17]
Capitalize Ruby in last line below. 

********
Relating Tables with Foreign Keys
Continuing the posts and authors examples, you could say that an author has many posts. The reciprocal of this would be that a post belongs to an author. Now we need to figure out how we can represent that relationship within the constraints of SQLite. If you were writing just plain ruby, how

**Comment by jenmyers** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
