### ISSUE TITLE
"Tables" Not "Rows"

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/table-relations#18]
Hi this should read "tables" not "rows".   
I'd written out diagrams over and over and over and couldn't figure out how 'rows' for Author and Post would be plausible. 

Line # 7 : change 'rows" to "tables" .  "figure out how to related two rows ( a Post and an Author) using only...." 
*********Relating Tables with Foreign Keys
Continuing the posts and authors examples, you could say that an author has many posts. The reciprocal of this would be that a post belongs to an author. Now we need to figure out how we can represent that relationship within the constraints of SQLite. If you were writing just plain ruby, how would you represent this relationship? In our Author class we would have an array of Post objects. Our Post object would have a single attribute that holds its Author. This is great in Ruby, but there is no data type for arrays in SQL. You can only have INTEGER, FLOAT, and TEXT. So developers had to figure out how to relate two rows (a Post and an Author) using only those data types. Is there any way we can convert an INTEGER into a specific row in a table? OH YEAH.

**Comment by jenmyers** [comment]
Hi there,

Thank you for your feedback! In this case, we're still discussing relating the rows of the tables, so the text is accurate.

As always, thanks for contributing! 💙
